# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2022-08-16 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voice_core", "0059_auto_20220802_1330"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voicemission",
            name="conversion_bonus_scheme",
        ),
    ]