# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2022-08-16 17:04
from __future__ import unicode_literals

import datetime
from _decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("voice_core", "0060_remove_voicemission_conversion_bonus_scheme"),
        ("compensation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversionbonusscheme",
            name="attribution_source",
        ),
        migrations.RemoveField(
            model_name="conversionbonusslab",
            name="minimum_conversion_percentage",
        ),
        migrations.AddField(
            model_name="conversionbonusscheme",
            name="data_source",
            field=models.CharField(
                choices=[("internal", "Internal"), ("customer", "Customer")],
                default="internal",
                help_text="The type of data source for disbursing conversion bonus for the scheme",
                max_length=20,
                verbose_name="Conversion data source",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversionbonusscheme",
            name="voice_mission",
            field=models.ForeignKey(
                default=747,
                help_text="Voice Mission marked with L2 or L3 use cases associated with the scheme",
                on_delete=django.db.models.deletion.PROTECT,
                to="voice_core.VoiceMission",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversionbonusslab",
            name="maximum_conversion_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Maximum conversion percentage for the slab",
                max_digits=4,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversionbonusscheme",
            name="budget_available",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Budget available (in INR) for conversion bonus of the cycle in the applicable date range",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conversionbonusscheme",
            name="renewal_factor",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of cycles for which this scheme should run. If number X is selcted, this scheme would continuosly run for X cycles.",
            ),
        ),
    ]