name: Django Migrations Linter

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    migrations_linter_job:
        runs-on: ubuntu-latest
        name: Alert for checking breaking migrations
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v14.6

            - name: List all changed files
              run: |
                  for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                    echo "$file was changed"
                  done
                  echo ${{ steps.changed-files.outputs.all_changed_files }}

            - name: setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.5.9
            - name: Run migrations linter
              run: |
                  python linter.py ${{ steps.changed-files.outputs.all_changed_files }}

